### ISSUE TITLE
set relativenumber question

### ISSUE THREAD

**Issue by oldtimeguitarguy** [prendradjaja/vim-vertigo#5]
I was wondering if you had a suggestion about how I could do this - maybe an autocmd?

I don't like to use line numbers, relative or otherwise. HOWEVER, it is very helpful to have relative numbers turned on when using your awesome plugin.

My goal is to make it so that when I trigger the plugin, it turns relative numbers on, and after the plugin has closed or has jumped the cursor, it turns relative numbers back off.

I was able to turn relative numbers on before the plugin triggers as a part of the key mapping, but I wasn't able to turn it back off AFTER the plugin finishes. When I put it in the mapping, it does it consecutively and doesn't wait for the plugin to finish.

Any suggestions would be much appreciated. Thank you.

**Comment by prendradjaja** [comment]
Instead of putting `:set number` and `:set nonumber` in your mapping, if you're willing to edit the plugin, you can put them at the top and bottom of the `s:Vertigo()` function.

**Comment by oldtimeguitarguy** [comment]
I thought I would just paste in here what I ended up doing, based on your recommendation...

```vim
function! s:Vertigo(motion, direction, mode)
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"* ARGUMENTS:
"    motion:     Which motion to use. ('j' or 'k')
"    direction:  A description of the motion. ('down' or 'up')
"                Used to prompt the user 'Jump down: ' or 'Jump up: '
"    mode:       An abbreviation for which Vim mode the user is in. ('n',
"                'v', or 'o', corresponding to :h map-modes)
"* EFFECTS:
"    Prompts the user to jump. After this function exits, the cursor is moved.
"    (if the user doesn't cancel)
"    Returns nothing.
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
  " **** RELATIVE NUMBER ADDITION #1 [START] ****
  let old_listchars=&listchars
  let old_list=&list
  let old_rnu=&rnu
  set listchars=tab:..,space:.
  set rnu
  set list
  " **** RELATIVE NUMBER ADDITION #1 [END] ****

  " If used in visual mode, Vim exited visual mode in order to get here.
  " Re-enter visual mode.
  if a:mode == 'v'
    normal! gv
  endif

  " If using absolute numbering, use an absolute jump. Otherwise, (if using
  " relative numbering, or no line numbering at all) use a relative jump.
  if s:UsingAbsoluteNumbering()
    call s:PromptAbsoluteJump(a:mode)
  else
    call s:PromptRelativeJump(a:motion, a:direction, a:mode)
  endif

  " **** RELATIVE NUMBER ADDITION #2 [START] ****
  let &list=old_list
  let &rnu=old_rnu
  let &listchars=old_listchars
  unlet old_list
  unlet old_rnu
  unlet old_listchars
  " **** RELATIVE NUMBER ADDITION #2 [END] ****
endfunction
```
